USE beautydb;

INSERT INTO Categories (name, createdAt, updatedAt) VALUES
  ('Skincare', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Makeup', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Perfume', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Nails', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Hair', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO Makers (name, createdAt, updatedAt) VALUES
  ('Jo Malone', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Oribe', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('AmorePacific', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('RetinA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('La Mer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Kate Somerville', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('R+Co', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SK-II', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Sunday Riley', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Shiseido', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Bioderma', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Burberry', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('LaNeige', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Mario Badescu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Charlotte Tilbury', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('MoroccanOil', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Bio-Oil', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Byredo Parfums', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Make Up For Ever', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Bite', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Givenchy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Anastasia Beverly Hills', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Marc Jacobs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('St. Topez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Urban Decay', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Benefit', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('OPI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Butter', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Smashbox', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Bobbi Brown', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rms', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Sephora', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Lipstick Queen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Topshop', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('nails, inc.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Babor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Murad', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Living Proof', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('drybar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('karina', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Glossier', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Cle de Peau', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('it Cosmetics', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Nars', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Sisley', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Amazing Cosmetics', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Nordstrom', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Avst Environ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Valmont', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Cellcomet', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Biologique Recherche', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('CO Bigelow', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('fresh', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Boscia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Yon-Ka', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO Tags (tag, createdAt, updatedAt) VALUES 
  ('Barrow', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Jetset', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Korea', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Cult', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Travel Size', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Hand', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Lotion', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Hair', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Face', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Facewash', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Perfume', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Eye', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Mask', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Night', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO Products (name, color, notes, size, createdAt, updatedAt, CategoryId, MakerId) VALUES
  ('Vitamin E Hand Treatment', NULL, 'Adam has this.', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Jo Malone')),
  ('Dry Texturizing Spray', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Hair'), (SELECT id FROM Makers WHERE name='Oribe')),
  ('Treatment Cleansing Foam', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='AmorePacific')),
  ('RetinA', NULL, 'Super strong. Don\'t use more than 3x/week', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='RetinA')),
  ('The Moisturizing Lotion', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='La Mer')),
  ('The Moisturizing Cream', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='La Mer')),
  ('ExfoliKate', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Kate Somerville')),
  ('Aircraft Pomade', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Hair'), (SELECT id FROM Makers WHERE name='R+Co')),
  ('Facial Treatment Clear Lotion', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='SK-II')),
  ('Start Over Active Eye Gel Cream', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Sunday Riley')),
  ('Luna Sleeping Night Oil', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Sunday Riley')),
  ('Ultimate Sun Protection Lotion+', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Shiseido')),
  ('Créaline H2O', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Bioderma')),
  ('Olio Lusso', NULL, 'Almost out', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Robin')),
  ('Clinical Clearing Gel', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Clinique')),
  ('Fresh Glow', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Burberry')),
  ('Water Sleeping Mask', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='LaNeige')),
  ('Vitamen C Serum', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Mario Badescu')),
  ('Charlotte\'s Magic Cream', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Charlotte Tilbury')),
  ('Facial Treatment Essence', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='SK-II')),
  ('Agron Treatment', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Hair'), (SELECT id FROM Makers WHERE name='MoroccanOil')),
  ('PurCellin Oil', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Bio-Oil')),
  ('Mojave Ghost', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Perfume'), (SELECT id FROM Makers WHERE name='Byredo Parfums')),
  ('Aqua Liner', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Make Up For Ever')),
  ('Matte Creme Lip Crayon', 'Fraise', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Bite')),
  ('Noir Couture Volume Mascara', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Givenchy')),
  ('Effortless Kohl Eyeliner', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Burberry')),
  ('Brow Wiz', NULL, 'Prefer compared to shadow.', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Anastasia Beverly Hills')),
  ('Gel Crayon', 'Silver', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Marc Jacobs')),
  ('Lip Definer', 'Rosewood', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Burberry')),
  ('Eye Definer', 'Midnight Ash', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Burberry')),
  ('Skin Illuminator', 'Gold', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='St. Topez')),
  ('Naked 2', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Urban Decay')),
  ('Sugarbomb', NULL, 'Good brush inside', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Benefit')),
  ('Sheer Foundation', NULL, 'Massive number of samples in large makeup bag under sink', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Burberry')),
  ('Nail Lacquer', 'Ballet Slippers', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Nails'), (SELECT id FROM Makers WHERE name='OPI')),
  ('Nail Polish', 'Artful Dodger', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Nails'), (SELECT id FROM Makers WHERE name='Butter')),
  ('Eye Palettte', 'Velvet Plum', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Bobbi Brown')),
  ('Eye Shadow', 'Slate', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Bobbi Brown')),
  ('Lip Cream', 'Bloom', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='rms')),
  ('Creaseless Cream Shadow', 'Grey Jeans', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Benefit')),
  ('Creamy Lip Color', 'Pale Mauve', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Bobbi Brown')),
  ('Lip Matte', 'Always Red', 'Full coverage', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Sephora')),
  ('Lipstick', 'Medival', 'Snake bite color', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Lipstick Queen')),
  ('Lips', 'Hot Pink', 'Wore in Kuala Lumpur', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Topshop')),
  ('Nails', 'Rainy Day', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Nails'), (SELECT id FROM Makers WHERE name='Topshop')),
  ('Nails', 'Seafoam', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Nails'), (SELECT id FROM Makers WHERE name='Topshop')),
  ('Nail Lacquer', 'Deep Navy (Old Bond Street)', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Nails'), (SELECT id FROM Makers WHERE name='nails, inc.')),
  ('Nail Lacquer', 'Purple(St. Martin\'s Lane)', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Nails'), (SELECT id FROM Makers WHERE name='nails, inc.')),
  ('Styling Paste', NULL, 'Under the sink', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Hair'), (SELECT id FROM Makers WHERE name='R+Co')),
  ('Intense Purifying Mask', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Babor')),
  ('Clarifying Toner', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Murad')),
  ('Glossy Wax', NULL, 'A bit thick for everday use.', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Hair'), (SELECT id FROM Makers WHERE name='R+Co')),
  ('Flex Shaping Hairspray', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Hair'), (SELECT id FROM Makers WHERE name='Living Proof')),
  ('Shine Pomade', NULL, 'Use when needing polished hair.', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Hair'), (SELECT id FROM Makers WHERE name='drybar')),
  ('Herbal Toner', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Hair'), (SELECT id FROM Makers WHERE name='karina')),
  ('Purifying Cleanser', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='karina')),
  ('Perfecting Skin Tint', 'Light', 'Super sheer; use when hot outside.', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Glossier')),
  ('Shade and Illuminate', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Tom Ford')),
  ('CC Cushion Compact', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='AmorePacific')),
  ('Sheer Eye Shadow', 'Almond', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Burberry')),
  ('Sheer Eye Shadow', 'Rosewood', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Burberry')),
  ('Sheer Eye Shadow', 'Trench', 'Base shadow', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Burberry')),
  ('Sheer Eye Shadow', 'Shell', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Burberry')),
  ('Concealer', NULL, 'Primary Concealer', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Cle de Peau')),
  ('Bye Bye Under Eye', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='it Cosmetics')),
  ('Velvet Matte', 'Cruella', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Nars')),
  ('Phyto-ombre Glow', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Sisley')),
  ('Concealer', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Amazing Cosmetics')),
  ('Eye Colour Cream', 'Dusky Mauve', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Burberry')),
  ('Light Glow', 'Earthy Blush', 'Can be used as eye shadow or bronzer', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Burberry')),
  ('Eye Gel', 'Black Ink', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Bobbi Brown')),
  ('Lip Color', 'Nude Cashmere', 'Primary Lipstick', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Burberry')),
  ('Lip Glow', 'Nude Beige', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Burberry')),
  ('Lip Glow', 'Oxblood', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Burberry')),
  ('Lip Glow', 'Nude Rose', 'Mix with Nude Kate or Nude Cashmere.', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Burberry')),
  ('Lipstick', 'Nude Kate', 'Mixed with Burberry Nude Rose gloss.', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Charlotte Tilbury')),
  ('The Lip Balm', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='La Mer')),
  ('Lip Balm', NULL, NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='La Mer')),
  ('Facial Treament Masque', NULL, 'In Fridge. Can be reused.', 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='SK-II')),
  ('3D Liner', 'Plum', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Smashbox')),
  ('3D Liner', 'Midnight', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Smashbox')),
  ('3D Liner', 'Navy', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Smashbox')),
  ('3D Liner', 'Light Grey', NULL, 'Full', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Makeup'), (SELECT id FROM Makers WHERE name='Smashbox')),
  ('Facial Treatment Clear Lotion', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='SK-II')),
  ('Body Gel Moussant', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Jo Malone')),
  ('English Pair and Freesia Cologne', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Perfume'), (SELECT id FROM Makers WHERE name='Jo Malone')),
  ('The Treatment Lotion', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='La Mer')),
  ('The Intensive Revitalizing Mask', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='La Mer')),
  ('Future Response Age Defense Creme', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='AmorePacific')),
  ('Make-Up Remover Wipes', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Nordstrom')),
  ('Eye Gel', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Avst Environ')),
  ('Hydrating Exfoliant', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Avst Environ')),
  ('Signature Shampoo and Masque', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Hair'), (SELECT id FROM Makers WHERE name='Oribe')),
  ('Color Shampoo and Conditioner', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Hair'), (SELECT id FROM Makers WHERE name='R+Co')),
  ('Prime Renew Pack', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Valmont')),
  ('Purifying Pack', NULL, 'Use on nose.', 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Valmont')),
  ('Prime Contour', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Valmont')),
  ('Creme Cellulaire Intensive', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Cellcomet')),
  ('Creme Aux Acides de Fruit', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Biologique Recherche')),
  ('Masque Biosensible', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Biologique Recherche')),
  ('Creme Metamorphique', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Biologique Recherche')),
  ('Body Lotion', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='CO Bigelow')),
  ('The Eye Concentrate', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='La Mer')),
  ('The Regenerating Serum', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='La Mer')),
  ('Peony & Blush Seude Body Creme', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Jo Malone')),
  ('Intensive Hand Renewal Creme', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='AmorePacific')),
  ('Rejuvenating Eye Treatment Gel', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='AmorePacific')),
  ('Age Defense Dual Eye Creme', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='AmorePacific')),
  ('Broad Spectrum SPF 30', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Murad')),
  ('Lotus Youth Preserve Face Cream', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='fresh')),
  ('Detoxifying Cleanser', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Boscia')),
  ('Luminizing Black Mask', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Boscia')),
  ('Corseting Serum', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Valmont')),
  ('Revitalizing Black Hydration Gel', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Boscia')),
  ('Lotion Yon-Ka', NULL, NULL, 'Travel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM Categories WHERE name='Skincare'), (SELECT id FROM Makers WHERE name='Yon-Ka'));

INSERT INTO Site (name, url, createdAt, updatedAt) VALUES
  ('Into the Gloss', 'https://wwww.intothegloss.com/', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Lisa Eldridge', 'http://www.lisaeldridge.com/', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Refinery29-Beauty Blogs', 'http://www.refinery29.com/beauty-blogs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Beauty Banter', 'http://beautybanter.com/', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Dasha Edelich, Edelich', 'http://edelich.com/', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
